export interface DocumentType {
  id: string;
  date: string;
  title: string;
  code: string;
  refNumber: string;
  createdAt: string;
  issuedDate: string;
  summary: string;
  urgency: string;
  confidentiality: string;
  type: string;
  authority: string;
  field: string;
  signer: string;
  recipients?: string;
  file: string;
  pages: number;
}

export const documents: DocumentType[] = [
  {
    id: '45/2020/TT-BGDDT',
    date: '11-11-2020',
    title: 'Thông tư ban hành Quy chế xét tặng Giải thưởng khoa học và công nghệ dành cho giảng viên trẻ và sinh viên trong cơ sở giáo dục đại học',
    code: 'DEN2611',
    refNumber: '452/QD-TTg (208/SY-UBND)',
    createdAt: '2025-03-18 13:43:57',
    issuedDate: '2025-02-27',
    summary: 'Quyết định phê duyệt quy hoạch mạng lưới cơ sở giáo dục đại học và sư phạm thời kỳ 2021-2030, tầm nhìn đến 2050',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-tu',
    authority: 'bo-giao-duc-dao-tao',
    field: 'dao-tao',
    signer: 'Lê Thanh Long',
    recipients: 'Các trường đại học',
    file: '452_QD_TTg.pdf',
    pages: 23
  },
  {
    id: '2025/CV-BGDDT',
    date: '10-03-2025',
    title: 'Công văn hướng dẫn triển khai công tác tuyển sinh năm 2025',
    code: 'DEN2650',
    refNumber: '500/CV-BGDDT',
    createdAt: '2025-03-21 10:00:00',
    issuedDate: '2025-03-20',
    summary: 'Hướng dẫn công tác tuyển sinh năm 2025 cho các trường đại học, cao đẳng',
    urgency: 'Khẩn',
    confidentiality: 'Bình thường',
    type: 'cong-van',
    authority: 'bo-giao-duc-dao-tao',
    field: 'dao-tao',
    signer: 'Trần Văn B',
    recipients: 'Các sở giáo dục và đào tạo, các trường đại học',
    file: '500_CV_BGDDT.pdf',
    pages: 12
  },
  {
    id: '39/2020/TT-BGDDT',
    date: '09-10-2020',
    title: 'Thông tư Quy định về tiêu chuẩn đánh giá chất lượng chương trình đào tạo từ xa trình độ đại học',
    code: 'DEN2612',
    refNumber: '453/QD-TTg (209/SY-UBND)',
    createdAt: '2025-03-19 09:15:30',
    issuedDate: '2025-02-28',
    summary: 'Quy định tiêu chuẩn đánh giá chất lượng đào tạo từ xa',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-tu',
    authority: 'bo-giao-duc-dao-tao',
    field: 'dao-tao',
    signer: 'Nguyễn Văn A',
    recipients: 'Các trường đại học',
    file: '453_QD_TTg.pdf',
    pages: 15
  },
  {
    id: '23/2025/QD-BGDDT',
    date: '15-02-2025',
    title: 'Quyết định thành lập Hội đồng khoa học cấp Bộ',
    code: 'QD0023',
    refNumber: '23/QD-BGDDT',
    createdAt: '2025-02-15 09:30:00',
    issuedDate: '2025-02-14',
    summary: 'Thành lập Hội đồng khoa học ngành giáo dục',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'quyet-dinh',
    authority: 'bo-giao-duc-dao-tao',
    field: 'khoa-hoc',
    signer: 'Trần Thị B',
    recipients: 'Các sở GD&ĐT',
    file: '23_QD_BGDDT.pdf',
    pages: 4
  },
  {
    id: '12/2025/NQ-CP',
    date: '01-03-2025',
    title: 'Nghị quyết về nâng cao chất lượng đào tạo đại học',
    code: 'NQ0012',
    refNumber: '12/NQ-CP',
    createdAt: '2025-03-01 10:00:00',
    issuedDate: '2025-02-28',
    summary: 'Đề ra các chính sách nâng cao chất lượng đào tạo',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'nghi-quyet',
    authority: 'chinh-phu',
    field: 'dao-tao',
    signer: 'Nguyễn Văn C',
    recipients: 'Các trường đại học',
    file: '12_NQ_CP.pdf',
    pages: 6
  },
  {
    id: '05/2025/CT-TTg',
    date: '05-01-2025',
    title: 'Chỉ thị về việc triển khai công tác giáo dục an toàn giao thông',
    code: 'CT0005',
    refNumber: '05/CT-TTg',
    createdAt: '2025-01-05 07:30:00',
    issuedDate: '2025-01-04',
    summary: 'Tăng cường tuyên truyền giáo dục ATGT trong trường học',
    urgency: 'Khẩn',
    confidentiality: 'Bình thường',
    type: 'chi-thi',
    authority: 'chinh-phu',
    field: 'hanh-chinh',
    signer: 'Phạm Minh Chính',
    recipients: 'Các tỉnh thành',
    file: '05_CT_TTg.pdf',
    pages: 3
  },
  {
    id: '09/2025/TB-BGDDT',
    date: '01-02-2025',
    title: 'Thông báo nghỉ Tết Nguyên đán năm 2025',
    code: 'TB0009',
    refNumber: '09/TB-BGDDT',
    createdAt: '2025-02-01 08:00:00',
    issuedDate: '2025-01-30',
    summary: 'Lịch nghỉ Tết dành cho sinh viên và cán bộ ngành giáo dục',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-bao',
    authority: 'bo-giao-duc-dao-tao',
    field: 'hanh-chinh',
    signer: 'Nguyễn Văn D',
    recipients: 'Các trường đại học, cao đẳng',
    file: '09_TB_BGDDT.pdf',
    pages: 1
  },
  {
    id: '01/2025/L-CP',
    date: '10-04-2025',
    title: 'Luật Giáo dục Đại học sửa đổi năm 2025',
    code: 'L0001',
    refNumber: '01/L-CP',
    createdAt: '2025-04-10 11:00:00',
    issuedDate: '2025-04-09',
    summary: 'Sửa đổi, bổ sung một số điều của Luật Giáo dục Đại học',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'luat-phap-lenh',
    authority: 'chinh-phu',
    field: 'thanh-tra-phap-che',
    signer: 'Trần Quốc Hội',
    recipients: 'Các cơ quan liên quan',
    file: '01_L_CP.pdf',
    pages: 18
  },
  {
    id: '02/2025/KH-BGDDT',
    date: '20-02-2025',
    title: 'Kế hoạch triển khai chương trình giáo dục phổ thông mới',
    code: 'KH0002',
    refNumber: '02/KH-BGDDT',
    createdAt: '2025-02-20 09:00:00',
    issuedDate: '2025-02-19',
    summary: 'Chi tiết kế hoạch triển khai chương trình giáo dục phổ thông',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'ke-hoach',
    authority: 'bo-giao-duc-dao-tao',
    field: 'dao-tao',
    signer: 'Lê Văn Kế',
    recipients: 'Các phòng giáo dục',
    file: '02_KH_BGDDT.pdf',
    pages: 5
  },
  {
    id: '12/2025/ND-CP',
    date: '10-03-2025',
    title: 'Nghị định quy định về tuyển sinh đại học',
    code: 'ND0012',
    refNumber: '12/ND-CP',
    createdAt: '2025-03-10 08:30:00',
    issuedDate: '2025-03-09',
    summary: 'Quy định mới về hình thức và điều kiện tuyển sinh',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'nghi-dinh',
    authority: 'chinh-phu',
    field: 'dao-tao',
    signer: 'Nguyễn Văn Chính',
    recipients: 'Các trường đại học',
    file: '12_ND_CP.pdf',
    pages: 7
  },
  {
    id: '03/2025/TT-BGDDT',
    date: '12-03-2025',
    title: 'Tờ trình đề xuất kinh phí nâng cấp cơ sở vật chất',
    code: 'TT0003',
    refNumber: '03/TT-BGDDT',
    createdAt: '2025-03-12 08:00:00',
    issuedDate: '2025-03-11',
    summary: 'Đề xuất ngân sách xây dựng cơ sở vật chất giáo dục',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'to-trinh',
    authority: 'bo-giao-duc-dao-tao',
    field: 'co-so-vat-chat-xay-dung-co-ban',
    signer: 'Nguyễn Thị Lan',
    recipients: 'Bộ Tài chính',
    file: '03_TT_BGDDT.pdf',
    pages: 3
  },
  {
    id: '07/2025/HD-BGDDT',
    date: '22-03-2025',
    title: 'Hướng dẫn sử dụng phần mềm tuyển sinh trực tuyến',
    code: 'HD0007',
    refNumber: '07/HD-BGDDT',
    createdAt: '2025-03-22 10:00:00',
    issuedDate: '2025-03-21',
    summary: 'Chi tiết quy trình sử dụng phần mềm xét tuyển trực tuyến',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'huong-dan',
    authority: 'bo-giao-duc-dao-tao',
    field: 'cong-nghe',
    signer: 'Lê Quốc Kỹ',
    recipients: 'Các trường đại học',
    file: '07_HD_BGDDT.pdf',
    pages: 9
  },
  {
    id: '10/2025/QC-BGDDT',
    date: '28-03-2025',
    title: 'Quy chế hoạt động của Hội đồng trường',
    code: 'QC0010',
    refNumber: '10/QC-BGDDT',
    createdAt: '2025-03-28 14:00:00',
    issuedDate: '2025-03-27',
    summary: 'Quy định vai trò, nhiệm vụ và cơ cấu tổ chức Hội đồng trường',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'quy-che',
    authority: 'bo-giao-duc-dao-tao',
    field: 'to-chuc-can-bo',
    signer: 'Đào Thị Hương',
    recipients: 'Các trường đại học',
    file: '10_QC_BGDDT.pdf',
    pages: 6
  },
  {
    id: '11/2025/CT-BGDDT',
    date: '01-04-2025',
    title: 'Chương trình đổi mới sáng tạo trong giáo dục đại học',
    code: 'CT0011',
    refNumber: '11/CT-BGDDT',
    createdAt: '2025-04-01 09:00:00',
    issuedDate: '2025-03-31',
    summary: 'Kế hoạch đổi mới sáng tạo toàn diện giáo dục đại học',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'chuong-trinh',
    authority: 'bo-giao-duc-dao-tao',
    field: 'dao-tao',
    signer: 'Phạm Văn Khôi',
    recipients: 'Các cơ sở đào tạo',
    file: '11_CT_BGDDT.pdf',
    pages: 8
  },
  {
    id: '01/2025/CV-HC',
    date: '10-01-2025',
    title: 'Công văn triển khai công tác hành chính đầu năm',
    code: 'CV-HC-001',
    refNumber: '01/CV-HC',
    createdAt: '2025-01-10 08:00:00',
    issuedDate: '2025-01-09',
    summary: 'Hướng dẫn thực hiện nhiệm vụ hành chính trong học kỳ 2',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'cong-van',
    authority: 'bo-giao-duc-dao-tao',
    field: 'hanh-chinh',
    signer: 'Nguyễn Văn A',
    recipients: 'Các phòng ban',
    file: 'CV_HC_01.pdf',
    pages: 3
  },
  {
    id: '02/2025/QD-TDKT',
    date: '20-01-2025',
    title: 'Quyết định khen thưởng cán bộ có thành tích xuất sắc',
    code: 'QD-TDKT-002',
    refNumber: '02/QD-TDKT',
    createdAt: '2025-01-20 09:15:00',
    issuedDate: '2025-01-19',
    summary: 'Tuyên dương các cá nhân xuất sắc năm 2024',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'quyet-dinh',
    authority: 'bo-giao-duc-dao-tao',
    field: 'thi-dua',
    signer: 'Trần Thị B',
    recipients: 'Cán bộ ngành giáo dục',
    file: 'QD_TDKT_02.pdf',
    pages: 2
  },
  {
    id: '03/2025/TT-GD',
    date: '25-01-2025',
    title: 'Thông tư hướng dẫn chuẩn đầu ra đại học',
    code: 'TT-GD-003',
    refNumber: '03/TT-GD',
    createdAt: '2025-01-25 10:00:00',
    issuedDate: '2025-01-24',
    summary: 'Ban hành chuẩn đầu ra cho các ngành đào tạo đại học',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-tu',
    authority: 'bo-giao-duc-dao-tao',
    field: 'dao-tao',
    signer: 'Lê Văn C',
    recipients: 'Các trường đại học',
    file: 'TT_GD_03.pdf',
    pages: 5
  },
  {
    id: '04/2025/QD-KHCN',
    date: '28-01-2025',
    title: 'Quyết định phê duyệt đề tài khoa học cấp Bộ',
    code: 'QD-KHCN-004',
    refNumber: '04/QD-KHCN',
    createdAt: '2025-01-28 11:00:00',
    issuedDate: '2025-01-27',
    summary: 'Danh sách đề tài nghiên cứu khoa học được phê duyệt năm 2025',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'quyet-dinh',
    authority: 'bo-giao-duc-dao-tao',
    field: 'khoa-hoc',
    signer: 'Phạm Thị D',
    recipients: 'Các cơ sở nghiên cứu',
    file: 'QD_KHCN_04.pdf',
    pages: 4
  },
  {
    id: '05/2025/HD-CNTT',
    date: '30-01-2025',
    title: 'Hướng dẫn chuyển đổi số trong quản lý giáo dục',
    code: 'HD-CNTT-005',
    refNumber: '05/HD-CNTT',
    createdAt: '2025-01-30 09:00:00',
    issuedDate: '2025-01-29',
    summary: 'Thực hiện chuyển đổi số toàn diện trong quản lý trường học',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'huong-dan',
    authority: 'bo-giao-duc-dao-tao',
    field: 'cong-nghe',
    signer: 'Đỗ Văn E',
    recipients: 'Phòng CNTT các đơn vị',
    file: 'HD_CNTT_05.pdf',
    pages: 6
  },
  {
    id: '06/2025/TT-TC',
    date: '02-02-2025',
    title: 'Thông tư quy định sử dụng kinh phí đào tạo',
    code: 'TT-TC-006',
    refNumber: '06/TT-TC',
    createdAt: '2025-02-02 08:00:00',
    issuedDate: '2025-02-01',
    summary: 'Hướng dẫn sử dụng và quyết toán kinh phí đào tạo',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-tu',
    authority: 'bo-giao-duc-dao-tao',
    field: 'ke-hoach-tai-chinh',
    signer: 'Ngô Thị F',
    recipients: 'Phòng tài chính các trường',
    file: 'TT_TC_06.pdf',
    pages: 5
  },
  {
    id: '07/2025/TT-CSVC',
    date: '05-02-2025',
    title: 'Thông tư hướng dẫn quản lý trang thiết bị giáo dục',
    code: 'TT-CSVC-007',
    refNumber: '07/TT-CSVC',
    createdAt: '2025-02-05 09:30:00',
    issuedDate: '2025-02-04',
    summary: 'Quy định mua sắm, quản lý tài sản giáo dục',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-tu',
    authority: 'bo-giao-duc-dao-tao',
    field: 'co-so-vat-chat',
    signer: 'Bùi Văn G',
    recipients: 'Phòng cơ sở vật chất',
    file: 'TT_CSVC_07.pdf',
    pages: 4
  },
  {
    id: '08/2025/CT-HTQT',
    date: '07-02-2025',
    title: 'Chỉ thị đẩy mạnh hợp tác quốc tế trong giáo dục',
    code: 'CT-HTQT-008',
    refNumber: '08/CT-HTQT',
    createdAt: '2025-02-07 08:00:00',
    issuedDate: '2025-02-06',
    summary: 'Phát triển hợp tác giáo dục với các nước',
    urgency: 'Khẩn',
    confidentiality: 'Bình thường',
    type: 'chi-thi',
    authority: 'bo-giao-duc-dao-tao',
    field: 'hop-tac-quoc-te',
    signer: 'Vũ Thị H',
    recipients: 'Các trường đại học',
    file: 'CT_HTQT_08.pdf',
    pages: 3
  },
  {
    id: '09/2025/TT-CSXD',
    date: '10-02-2025',
    title: 'Thông tư hướng dẫn xây dựng cơ bản cho trường học',
    code: 'TT-CSXD-009',
    refNumber: '09/TT-CSXD',
    createdAt: '2025-02-10 08:45:00',
    issuedDate: '2025-02-09',
    summary: 'Hướng dẫn đầu tư xây dựng cơ sở giáo dục',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-tu',
    authority: 'bo-giao-duc-dao-tao',
    field: 'co-so-vat-chat-xay-dung-co-ban',
    signer: 'Trần Văn I',
    recipients: 'Các sở GD&ĐT',
    file: 'TT_CSXD_09.pdf',
    pages: 5
  },
  {
    id: '10/2025/HD-CTSV',
    date: '12-02-2025',
    title: 'Hướng dẫn hỗ trợ sinh viên khó khăn',
    code: 'HD-CTSV-010',
    refNumber: '10/HD-CTSV',
    createdAt: '2025-02-12 09:00:00',
    issuedDate: '2025-02-11',
    summary: 'Hỗ trợ học phí và chỗ ở cho sinh viên nghèo',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'huong-dan',
    authority: 'bo-giao-duc-dao-tao',
    field: 'cong-tac-hoc-sinh-sinh-vien',
    signer: 'Nguyễn Thị K',
    recipients: 'Phòng CTSV',
    file: 'HD_CTSV_10.pdf',
    pages: 4
  },
  {
    id: '11/2025/QD-TCCB',
    date: '14-02-2025',
    title: 'Quyết định bổ nhiệm cán bộ quản lý mới',
    code: 'QD-TCCB-011',
    refNumber: '11/QD-TCCB',
    createdAt: '2025-02-14 08:30:00',
    issuedDate: '2025-02-13',
    summary: 'Phê duyệt danh sách bổ nhiệm lãnh đạo các đơn vị',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'quyet-dinh',
    authority: 'bo-giao-duc-dao-tao',
    field: 'to-chuc-can-bo',
    signer: 'Nguyễn Văn L',
    recipients: 'Các phòng chức năng',
    file: 'QD_TCCB_11.pdf',
    pages: 2
  },
  {
    id: '12/2025/TT-TTPC',
    date: '16-02-2025',
    title: 'Thông tư về công tác thanh tra kiểm tra nội bộ',
    code: 'TT-TTPC-012',
    refNumber: '12/TT-TTPC',
    createdAt: '2025-02-16 09:00:00',
    issuedDate: '2025-02-15',
    summary: 'Quy trình thực hiện kiểm tra định kỳ nội bộ',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-tu',
    authority: 'bo-giao-duc-dao-tao',
    field: 'thanh-tra-phap-che',
    signer: 'Lê Văn M',
    recipients: 'Các trường',
    file: 'TT_TTPC_12.pdf',
    pages: 4
  },
  {
    id: '13/2025/QD-DT',
    date: '18-02-2025',
    title: 'Quyết định tổ chức đại hội đoàn trường',
    code: 'QD-DT-013',
    refNumber: '13/QD-DT',
    createdAt: '2025-02-18 10:00:00',
    issuedDate: '2025-02-17',
    summary: 'Phê duyệt kế hoạch tổ chức đại hội Đoàn năm học 2025',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'quyet-dinh',
    authority: 'bo-giao-duc-dao-tao',
    field: 'doan-the',
    signer: 'Nguyễn Văn N',
    recipients: 'Các đơn vị đoàn thể',
    file: 'QD_DT_13.pdf',
    pages: 2
  },
  {
    id: '14/2025/HD-KDCL',
    date: '20-02-2025',
    title: 'Hướng dẫn kiểm định chất lượng đại học',
    code: 'HD-KDCL-014',
    refNumber: '14/HD-KDCL',
    createdAt: '2025-02-20 09:30:00',
    issuedDate: '2025-02-19',
    summary: 'Quy trình kiểm định chất lượng trường đại học công lập',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'huong-dan',
    authority: 'bo-giao-duc-dao-tao',
    field: 'kiem-dinh-chat-luong-GDĐH',
    signer: 'Nguyễn Thị O',
    recipients: 'Các đơn vị kiểm định',
    file: 'HD_KDCL_14.pdf',
    pages: 6
  },
  {
    id: '15/2025/TB-KHAC',
    date: '22-02-2025',
    title: 'Thông báo tổ chức hội thao ngành giáo dục',
    code: 'TB-KHAC-015',
    refNumber: '15/TB-KHAC',
    createdAt: '2025-02-22 08:00:00',
    issuedDate: '2025-02-21',
    summary: 'Thời gian và địa điểm tổ chức hội thao toàn quốc',
    urgency: 'Bình thường',
    confidentiality: 'Bình thường',
    type: 'thong-bao',
    authority: 'bo-giao-duc-dao-tao',
    field: 'cac-hoat-dong-khac',
    signer: 'Nguyễn Văn P',
    recipients: 'Toàn ngành',
    file: 'TB_KHAC_15.pdf',
    pages: 3
  }
];

export const categories = [
  { id: 'cong-van', name: 'Công văn - Văn bản điều hành khác' },
  { id: 'quyet-dinh', name: 'Quyết định' },
  { id: 'nghi-quyet', name: 'Nghị Quyết' },
  { id: 'thong-tu', name: 'Thông tư' },
  { id: 'chi-thi', name: 'Chỉ thị' },
  { id: 'thong-bao', name: 'Thông báo' },
  { id: 'luat-phap-lenh', name: 'Luật - Pháp lệnh' },
  { id: 'ke-hoach', name: 'Kế hoạch' },
  { id: 'nghi-dinh', name: 'Nghị định' },
  { id: 'to-trinh', name: 'Tờ trình' },
  { id: 'huong-dan', name: 'Hướng dẫn - Biểu mẫu' },
  { id: 'quy-che', name: 'Quy chế' },
  { id: 'chuong-trinh', name: 'Chương trình' }
];

export const activities = [
  { id: 'hanh-chinh', name: 'Hành chính - Tổng hợp' },
  { id: 'thi-dua', name: 'Thi đua - Khen thưởng' },
  { id: 'dao-tao', name: 'Đào tạo' },
  { id: 'khoa-hoc', name: 'Khoa học - Công nghệ - Môi trường' },
  { id: 'cong-nghe', name: 'Công nghệ Thông tin' },
  { id: 'ke-hoach-tai-chinh', name: 'Kế hoạch tài chính' },
  { id: 'co-so-vat-chat', name: 'Cơ sở vật chất' },
  { id: 'hop-tac-quoc-te', name: 'Hợp tác quốc tế' },
  { id: 'co-so-vat-chat-xay-dung-co-ban', name: 'Cơ sở vật chất - Xây dựng cơ bản' },
  { id: 'cong-tac-hoc-sinh-sinh-vien', name: 'Công tác học sinh - sinh viên' },
  { id: 'to-chuc-can-bo', name: 'Tổ chức - Cán bộ' },
  { id: 'thanh-tra-phap-che', name: 'Thanh tra - Pháp chế' },
  { id: 'doan-the', name: 'Đoàn thể' },
  { id: 'kiem-dinh-chat-luong-GDĐH', name: 'Kiểm định chất lượng GDDH' },
  { id: 'cac-hoat-dong-khac', name: 'Các hoạt động khác' }
];

export const issuingAgency = [
  { id: 'bo-chinh-tri', name: 'Bộ Chính trị' },
  { id: 'chinh-phu', name: 'Chính phủ' },
  { id: 'bo-nganh-khac', name: 'Bộ, ngành khác' },
  { id: 'bo-giao-duc-dao-tao', name: 'Bộ Giáo dục-đào tạo' },
  { id: 'dai-hoc-hue', name: 'Đại học Huế' },
  { id: 'ubnd-tinh/thanh-pho', name: 'UBND tỉnh/thành phố' }
];