name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # chạy khi push code lên main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t giavy/nextjs-hethongtravanban:latest .
          docker push giavy/nextjs-hethongtravanban:latest
